# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'micro_tomography_analyzer.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MicroTomographyAnalyzer(object):
    def setupUi(self, MicroTomographyAnalyzer):
        MicroTomographyAnalyzer.setObjectName("MicroTomographyAnalyzer")
        MicroTomographyAnalyzer.resize(931, 729)
        self.centralwidget = QtWidgets.QWidget(MicroTomographyAnalyzer)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_13.addWidget(self.line_2)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget_6 = QtWidgets.QWidget(self.splitter)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.display_stack = QtWidgets.QStackedWidget(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.display_stack.sizePolicy().hasHeightForWidth())
        self.display_stack.setSizePolicy(sizePolicy)
        self.display_stack.setObjectName("display_stack")
        self.page_slices = QtWidgets.QWidget()
        self.page_slices.setObjectName("page_slices")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_slices)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.slices = ImageDisplay(self.page_slices)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slices.sizePolicy().hasHeightForWidth())
        self.slices.setSizePolicy(sizePolicy)
        self.slices.setMinimumSize(QtCore.QSize(400, 0))
        self.slices.setText("")
        self.slices.setObjectName("slices")
        self.verticalLayout_3.addWidget(self.slices)
        self.display_stack.addWidget(self.page_slices)
        self.page_detected_columns = QtWidgets.QWidget()
        self.page_detected_columns.setObjectName("page_detected_columns")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.page_detected_columns)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.detected_columns = ImageDisplay(self.page_detected_columns)
        self.detected_columns.setText("")
        self.detected_columns.setObjectName("detected_columns")
        self.verticalLayout_12.addWidget(self.detected_columns)
        self.display_stack.addWidget(self.page_detected_columns)
        self.page_front_display = QtWidgets.QWidget()
        self.page_front_display.setObjectName("page_front_display")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.page_front_display)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.imbibition_front = ImageDisplay(self.page_front_display)
        self.imbibition_front.setText("")
        self.imbibition_front.setObjectName("imbibition_front")
        self.verticalLayout_15.addWidget(self.imbibition_front)
        self.display_stack.addWidget(self.page_front_display)
        self.verticalLayout_5.addWidget(self.display_stack)
        self.page_controls = QtWidgets.QWidget(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_controls.sizePolicy().hasHeightForWidth())
        self.page_controls.setSizePolicy(sizePolicy)
        self.page_controls.setObjectName("page_controls")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.page_controls)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.previous_display_page = QtWidgets.QPushButton(self.page_controls)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previous_display_page.sizePolicy().hasHeightForWidth())
        self.previous_display_page.setSizePolicy(sizePolicy)
        self.previous_display_page.setMaximumSize(QtCore.QSize(25, 16777215))
        self.previous_display_page.setObjectName("previous_display_page")
        self.horizontalLayout_7.addWidget(self.previous_display_page)
        self.next_display_page = QtWidgets.QPushButton(self.page_controls)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_display_page.sizePolicy().hasHeightForWidth())
        self.next_display_page.setSizePolicy(sizePolicy)
        self.next_display_page.setMaximumSize(QtCore.QSize(25, 16777215))
        self.next_display_page.setObjectName("next_display_page")
        self.horizontalLayout_7.addWidget(self.next_display_page)
        self.verticalLayout_5.addWidget(self.page_controls)
        self.widget_5 = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tools = QtWidgets.QStackedWidget(self.widget_5)
        self.tools.setObjectName("tools")
        self.page_slicing = QtWidgets.QWidget()
        self.page_slicing.setObjectName("page_slicing")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_slicing)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.group_slicing = QtWidgets.QGroupBox(self.page_slicing)
        self.group_slicing.setObjectName("group_slicing")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.group_slicing)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.group_slicing)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.widget_2 = QtWidgets.QWidget(self.group_slicing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.low_bound_dim1 = QtWidgets.QSpinBox(self.widget_2)
        self.low_bound_dim1.setMaximum(999999999)
        self.low_bound_dim1.setObjectName("low_bound_dim1")
        self.horizontalLayout_4.addWidget(self.low_bound_dim1)
        self.high_bound_dim1 = QtWidgets.QSpinBox(self.widget_2)
        self.high_bound_dim1.setMaximum(999999999)
        self.high_bound_dim1.setObjectName("high_bound_dim1")
        self.horizontalLayout_4.addWidget(self.high_bound_dim1)
        self.verticalLayout_6.addWidget(self.widget_2)
        self.label_3 = QtWidgets.QLabel(self.group_slicing)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.widget_3 = QtWidgets.QWidget(self.group_slicing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.low_bound_dim2 = QtWidgets.QSpinBox(self.widget_3)
        self.low_bound_dim2.setMaximum(999999999)
        self.low_bound_dim2.setObjectName("low_bound_dim2")
        self.horizontalLayout_5.addWidget(self.low_bound_dim2)
        self.high_bound_dim2 = QtWidgets.QSpinBox(self.widget_3)
        self.high_bound_dim2.setMaximum(999999999)
        self.high_bound_dim2.setObjectName("high_bound_dim2")
        self.horizontalLayout_5.addWidget(self.high_bound_dim2)
        self.verticalLayout_6.addWidget(self.widget_3)
        self.reset_slicing = QtWidgets.QPushButton(self.group_slicing)
        self.reset_slicing.setObjectName("reset_slicing")
        self.verticalLayout_6.addWidget(self.reset_slicing)
        self.apply_slicing = QtWidgets.QPushButton(self.group_slicing)
        self.apply_slicing.setObjectName("apply_slicing")
        self.verticalLayout_6.addWidget(self.apply_slicing)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.verticalLayout_9.addWidget(self.group_slicing)
        self.tools.addWidget(self.page_slicing)
        self.page_rotating = QtWidgets.QWidget()
        self.page_rotating.setObjectName("page_rotating")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_rotating)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_2 = QtWidgets.QGroupBox(self.page_rotating)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.rotation_angle = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.rotation_angle.setMinimum(-360.0)
        self.rotation_angle.setMaximum(360.0)
        self.rotation_angle.setObjectName("rotation_angle")
        self.verticalLayout_10.addWidget(self.rotation_angle)
        self.preview_rotation = QtWidgets.QCheckBox(self.groupBox_2)
        self.preview_rotation.setObjectName("preview_rotation")
        self.verticalLayout_10.addWidget(self.preview_rotation)
        self.apply_rotation = QtWidgets.QPushButton(self.groupBox_2)
        self.apply_rotation.setObjectName("apply_rotation")
        self.verticalLayout_10.addWidget(self.apply_rotation)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem2)
        self.verticalLayout_8.addWidget(self.groupBox_2)
        self.tools.addWidget(self.page_rotating)
        self.page_column_detection = QtWidgets.QWidget()
        self.page_column_detection.setObjectName("page_column_detection")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_column_detection)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox = QtWidgets.QGroupBox(self.page_column_detection)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_11.addWidget(self.label_4)
        self.z_for_mean_start = QtWidgets.QSpinBox(self.groupBox)
        self.z_for_mean_start.setMaximum(999999999)
        self.z_for_mean_start.setObjectName("z_for_mean_start")
        self.verticalLayout_11.addWidget(self.z_for_mean_start)
        self.z_for_mean_end = QtWidgets.QSpinBox(self.groupBox)
        self.z_for_mean_end.setMaximum(999999999)
        self.z_for_mean_end.setProperty("value", 1)
        self.z_for_mean_end.setObjectName("z_for_mean_end")
        self.verticalLayout_11.addWidget(self.z_for_mean_end)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_11.addWidget(self.label_5)
        self.threshold_column_detection = QtWidgets.QSpinBox(self.groupBox)
        self.threshold_column_detection.setMaximum(99)
        self.threshold_column_detection.setProperty("value", 30)
        self.threshold_column_detection.setObjectName("threshold_column_detection")
        self.verticalLayout_11.addWidget(self.threshold_column_detection)
        self.widget_8 = QtWidgets.QWidget(self.groupBox)
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.groupBox_9 = QtWidgets.QGroupBox(self.widget_8)
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.custom_clustering = QtWidgets.QRadioButton(self.groupBox_9)
        self.custom_clustering.setChecked(True)
        self.custom_clustering.setAutoExclusive(True)
        self.custom_clustering.setObjectName("custom_clustering")
        self.horizontalLayout_9.addWidget(self.custom_clustering)
        self.agglomerative_clustering = QtWidgets.QRadioButton(self.groupBox_9)
        self.agglomerative_clustering.setObjectName("agglomerative_clustering")
        self.horizontalLayout_9.addWidget(self.agglomerative_clustering)
        self.column_detection_preview_only = QtWidgets.QCheckBox(self.groupBox_9)
        self.column_detection_preview_only.setObjectName("column_detection_preview_only")
        self.horizontalLayout_9.addWidget(self.column_detection_preview_only)
        self.verticalLayout_14.addWidget(self.groupBox_9)
        self.groupBox_6 = QtWidgets.QGroupBox(self.widget_8)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.widget = QtWidgets.QWidget(self.groupBox_6)
        self.widget.setObjectName("widget")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_15.addWidget(self.label_11)
        self.mixing = QtWidgets.QSpinBox(self.widget)
        self.mixing.setMinimum(1)
        self.mixing.setProperty("value", 2)
        self.mixing.setDisplayIntegerBase(10)
        self.mixing.setObjectName("mixing")
        self.horizontalLayout_15.addWidget(self.mixing)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem3)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_15.addWidget(self.label_7)
        self.clip_limit = QtWidgets.QSpinBox(self.widget)
        self.clip_limit.setMinimum(1)
        self.clip_limit.setMaximum(100)
        self.clip_limit.setObjectName("clip_limit")
        self.horizontalLayout_15.addWidget(self.clip_limit)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem4)
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_15.addWidget(self.label_10)
        self.kernel_size = QtWidgets.QSpinBox(self.widget)
        self.kernel_size.setMinimum(1)
        self.kernel_size.setMaximum(99999)
        self.kernel_size.setProperty("value", 100)
        self.kernel_size.setObjectName("kernel_size")
        self.horizontalLayout_15.addWidget(self.kernel_size)
        self.verticalLayout_19.addWidget(self.widget)
        self.verticalLayout_14.addWidget(self.groupBox_6)
        self.verticalLayout_11.addWidget(self.widget_8)
        self.widget_7 = QtWidgets.QWidget(self.groupBox)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.start_column_detection = QtWidgets.QPushButton(self.widget_7)
        self.start_column_detection.setObjectName("start_column_detection")
        self.horizontalLayout_8.addWidget(self.start_column_detection)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.label_6 = QtWidgets.QLabel(self.widget_7)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.n_points_sampled = QtWidgets.QLineEdit(self.widget_7)
        self.n_points_sampled.setObjectName("n_points_sampled")
        self.horizontalLayout_8.addWidget(self.n_points_sampled)
        self.verticalLayout_11.addWidget(self.widget_7)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem6)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.tools.addWidget(self.page_column_detection)
        self.page_imbibition_front = QtWidgets.QWidget()
        self.page_imbibition_front.setObjectName("page_imbibition_front")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_imbibition_front)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.page_imbibition_front)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.sample_imbibition_front = QtWidgets.QPushButton(self.groupBox_4)
        self.sample_imbibition_front.setObjectName("sample_imbibition_front")
        self.verticalLayout_16.addWidget(self.sample_imbibition_front)
        self.line_3 = QtWidgets.QFrame(self.groupBox_4)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_16.addWidget(self.line_3)
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_16.addWidget(self.label_9)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.left_expected_value = QtWidgets.QSpinBox(self.groupBox_4)
        self.left_expected_value.setMaximum(999999999)
        self.left_expected_value.setObjectName("left_expected_value")
        self.horizontalLayout_13.addWidget(self.left_expected_value)
        self.right_expected_value = QtWidgets.QSpinBox(self.groupBox_4)
        self.right_expected_value.setMaximum(999999999)
        self.right_expected_value.setObjectName("right_expected_value")
        self.horizontalLayout_13.addWidget(self.right_expected_value)
        self.update_imbibiton_front = QtWidgets.QPushButton(self.groupBox_4)
        self.update_imbibiton_front.setObjectName("update_imbibiton_front")
        self.horizontalLayout_13.addWidget(self.update_imbibiton_front)
        self.verticalLayout_16.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem7)
        self.save_grayvalue_slopes = QtWidgets.QPushButton(self.groupBox_4)
        self.save_grayvalue_slopes.setObjectName("save_grayvalue_slopes")
        self.horizontalLayout_14.addWidget(self.save_grayvalue_slopes)
        self.verticalLayout_16.addLayout(self.horizontalLayout_14)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.page_imbibition_front)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.sampling_rule = QtWidgets.QComboBox(self.groupBox_5)
        self.sampling_rule.setObjectName("sampling_rule")
        self.sampling_rule.addItem("")
        self.sampling_rule.addItem("")
        self.horizontalLayout_10.addWidget(self.sampling_rule)
        self.start_sampling = QtWidgets.QPushButton(self.groupBox_5)
        self.start_sampling.setObjectName("start_sampling")
        self.horizontalLayout_10.addWidget(self.start_sampling)
        self.verticalLayout_17.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem8)
        self.label_8 = QtWidgets.QLabel(self.groupBox_5)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_11.addWidget(self.label_8)
        self.maxdist_extrema = QtWidgets.QSpinBox(self.groupBox_5)
        self.maxdist_extrema.setMaximum(999999999)
        self.maxdist_extrema.setProperty("value", 30)
        self.maxdist_extrema.setObjectName("maxdist_extrema")
        self.horizontalLayout_11.addWidget(self.maxdist_extrema)
        self.verticalLayout_17.addLayout(self.horizontalLayout_11)
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox_5)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 98, 66))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.polymer_level = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.polymer_level.setObjectName("polymer_level")
        self.verticalLayout_18.addWidget(self.polymer_level)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_17.addWidget(self.scrollArea)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem9)
        self.save_polymer_level = QtWidgets.QPushButton(self.groupBox_5)
        self.save_polymer_level.setObjectName("save_polymer_level")
        self.horizontalLayout_12.addWidget(self.save_polymer_level)
        self.verticalLayout_17.addLayout(self.horizontalLayout_12)
        self.verticalLayout_4.addWidget(self.groupBox_5)
        self.widget_4 = QtWidgets.QWidget(self.page_imbibition_front)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.pushButton = QtWidgets.QPushButton(self.widget_4)
        self.pushButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_6.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_2.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_6.addWidget(self.pushButton_2)
        self.verticalLayout_4.addWidget(self.widget_4)
        self.tools.addWidget(self.page_imbibition_front)
        self.verticalLayout_2.addWidget(self.tools)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.axis = QtWidgets.QComboBox(self.groupBox_3)
        self.axis.setObjectName("axis")
        self.axis.addItem("")
        self.axis.addItem("")
        self.axis.addItem("")
        self.horizontalLayout_3.addWidget(self.axis)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.verticalLayout_13.addWidget(self.splitter)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_13.addWidget(self.line)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget1.sizePolicy().hasHeightForWidth())
        self.widget1.setSizePolicy(sizePolicy)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loading_info_stack = QtWidgets.QStackedWidget(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loading_info_stack.sizePolicy().hasHeightForWidth())
        self.loading_info_stack.setSizePolicy(sizePolicy)
        self.loading_info_stack.setMaximumSize(QtCore.QSize(180, 16777215))
        self.loading_info_stack.setObjectName("loading_info_stack")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.page_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.file_info = QtWidgets.QLabel(self.page_3)
        self.file_info.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.file_info.setObjectName("file_info")
        self.horizontalLayout_2.addWidget(self.file_info)
        self.loading_info_stack.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.progress = QtWidgets.QProgressBar(self.page_4)
        self.progress.setMaximumSize(QtCore.QSize(180, 16777215))
        self.progress.setProperty("value", 0)
        self.progress.setObjectName("progress")
        self.verticalLayout.addWidget(self.progress)
        self.loading_info_stack.addWidget(self.page_4)
        self.horizontalLayout.addWidget(self.loading_info_stack)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem11)
        self.previous = QtWidgets.QPushButton(self.widget1)
        self.previous.setMinimumSize(QtCore.QSize(80, 0))
        self.previous.setMaximumSize(QtCore.QSize(80, 16777215))
        self.previous.setObjectName("previous")
        self.horizontalLayout.addWidget(self.previous)
        self.next = QtWidgets.QPushButton(self.widget1)
        self.next.setMinimumSize(QtCore.QSize(80, 0))
        self.next.setMaximumSize(QtCore.QSize(80, 16777215))
        self.next.setObjectName("next")
        self.horizontalLayout.addWidget(self.next)
        self.slice = QtWidgets.QSpinBox(self.widget1)
        self.slice.setMaximum(999999999)
        self.slice.setObjectName("slice")
        self.horizontalLayout.addWidget(self.slice)
        self.verticalLayout_13.addWidget(self.widget1)
        MicroTomographyAnalyzer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MicroTomographyAnalyzer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 931, 17))
        self.menubar.setObjectName("menubar")
        self.menuOpen = QtWidgets.QMenu(self.menubar)
        self.menuOpen.setObjectName("menuOpen")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MicroTomographyAnalyzer.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MicroTomographyAnalyzer)
        self.toolBar.setObjectName("toolBar")
        MicroTomographyAnalyzer.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtWidgets.QToolBar(MicroTomographyAnalyzer)
        self.toolBar_2.setObjectName("toolBar_2")
        MicroTomographyAnalyzer.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.actionOpen = QtWidgets.QAction(MicroTomographyAnalyzer)
        self.actionOpen.setObjectName("actionOpen")
        self.actionRotate = QtWidgets.QAction(MicroTomographyAnalyzer)
        self.actionRotate.setObjectName("actionRotate")
        self.actionDetect = QtWidgets.QAction(MicroTomographyAnalyzer)
        self.actionDetect.setObjectName("actionDetect")
        self.actionImbibition = QtWidgets.QAction(MicroTomographyAnalyzer)
        self.actionImbibition.setObjectName("actionImbibition")
        self.actionSave = QtWidgets.QAction(MicroTomographyAnalyzer)
        self.actionSave.setObjectName("actionSave")
        self.actionDisplay_xy_slices = QtWidgets.QAction(MicroTomographyAnalyzer)
        self.actionDisplay_xy_slices.setObjectName("actionDisplay_xy_slices")
        self.actionDisplay_xz_slices = QtWidgets.QAction(MicroTomographyAnalyzer)
        self.actionDisplay_xz_slices.setObjectName("actionDisplay_xz_slices")
        self.actionDisplay_yz_slices = QtWidgets.QAction(MicroTomographyAnalyzer)
        self.actionDisplay_yz_slices.setObjectName("actionDisplay_yz_slices")
        self.actionShow_slices = QtWidgets.QAction(MicroTomographyAnalyzer)
        self.actionShow_slices.setObjectName("actionShow_slices")
        self.actionShow_Detected_colum_view = QtWidgets.QAction(MicroTomographyAnalyzer)
        self.actionShow_Detected_colum_view.setObjectName("actionShow_Detected_colum_view")
        self.actionShow_columnwise_imbibition_front = QtWidgets.QAction(MicroTomographyAnalyzer)
        self.actionShow_columnwise_imbibition_front.setObjectName("actionShow_columnwise_imbibition_front")
        self.actionSlice_tensor = QtWidgets.QAction(MicroTomographyAnalyzer)
        self.actionSlice_tensor.setObjectName("actionSlice_tensor")
        self.actionOpen_Tensor = QtWidgets.QAction(MicroTomographyAnalyzer)
        self.actionOpen_Tensor.setObjectName("actionOpen_Tensor")
        self.menuOpen.addAction(self.actionOpen)
        self.menuOpen.addAction(self.actionOpen_Tensor)
        self.menuOpen.addSeparator()
        self.menuOpen.addAction(self.actionSlice_tensor)
        self.menuOpen.addAction(self.actionRotate)
        self.menuOpen.addAction(self.actionDetect)
        self.menuOpen.addAction(self.actionImbibition)
        self.menuOpen.addSeparator()
        self.menuOpen.addAction(self.actionSave)
        self.menuView.addAction(self.actionDisplay_xy_slices)
        self.menuView.addAction(self.actionDisplay_xz_slices)
        self.menuView.addAction(self.actionDisplay_yz_slices)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionShow_slices)
        self.menuView.addAction(self.actionShow_Detected_colum_view)
        self.menuView.addAction(self.actionShow_columnwise_imbibition_front)
        self.menubar.addAction(self.menuOpen.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSlice_tensor)
        self.toolBar.addAction(self.actionRotate)
        self.toolBar.addAction(self.actionDetect)
        self.toolBar.addAction(self.actionImbibition)

        self.retranslateUi(MicroTomographyAnalyzer)
        self.display_stack.setCurrentIndex(0)
        self.tools.setCurrentIndex(2)
        self.loading_info_stack.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MicroTomographyAnalyzer)

    def retranslateUi(self, MicroTomographyAnalyzer):
        _translate = QtCore.QCoreApplication.translate
        MicroTomographyAnalyzer.setWindowTitle(_translate("MicroTomographyAnalyzer", "Micro Tomography Analyzer"))
        self.previous_display_page.setText(_translate("MicroTomographyAnalyzer", "<"))
        self.next_display_page.setText(_translate("MicroTomographyAnalyzer", ">"))
        self.group_slicing.setTitle(_translate("MicroTomographyAnalyzer", "Slice tensor:"))
        self.label_2.setText(_translate("MicroTomographyAnalyzer", "Slice along first axis:"))
        self.label_3.setText(_translate("MicroTomographyAnalyzer", "Slice along second axis:"))
        self.reset_slicing.setText(_translate("MicroTomographyAnalyzer", "Reset preview"))
        self.apply_slicing.setText(_translate("MicroTomographyAnalyzer", "Recompute tensor"))
        self.groupBox_2.setTitle(_translate("MicroTomographyAnalyzer", "Rotate tensor:"))
        self.preview_rotation.setText(_translate("MicroTomographyAnalyzer", "Preview for current slice"))
        self.apply_rotation.setText(_translate("MicroTomographyAnalyzer", "Recompute tensor"))
        self.groupBox.setTitle(_translate("MicroTomographyAnalyzer", "Detect columns:"))
        self.label_4.setText(_translate("MicroTomographyAnalyzer", "Start/Stop slice for averaging:"))
        self.label_5.setText(_translate("MicroTomographyAnalyzer", "Threshold:"))
        self.groupBox_9.setTitle(_translate("MicroTomographyAnalyzer", "Clustering"))
        self.custom_clustering.setText(_translate("MicroTomographyAnalyzer", "Custom clustering"))
        self.agglomerative_clustering.setText(_translate("MicroTomographyAnalyzer", "Agglomerative Clustering"))
        self.column_detection_preview_only.setText(_translate("MicroTomographyAnalyzer", "preview only"))
        self.groupBox_6.setTitle(_translate("MicroTomographyAnalyzer", "Local contrast"))
        self.label_11.setText(_translate("MicroTomographyAnalyzer", "Mixing [%]"))
        self.label_7.setText(_translate("MicroTomographyAnalyzer", "Clip limit [%]"))
        self.label_10.setText(_translate("MicroTomographyAnalyzer", "Kernel size [px]"))
        self.start_column_detection.setText(_translate("MicroTomographyAnalyzer", "Start column detection"))
        self.label_6.setText(_translate("MicroTomographyAnalyzer", "Sampled points: "))
        self.groupBox_4.setTitle(_translate("MicroTomographyAnalyzer", "Find grayvalue slopes per pore:"))
        self.sample_imbibition_front.setText(_translate("MicroTomographyAnalyzer", "start"))
        self.label_9.setText(_translate("MicroTomographyAnalyzer", "Center position for measurements (expected value of interfaces):"))
        self.update_imbibiton_front.setText(_translate("MicroTomographyAnalyzer", "update"))
        self.save_grayvalue_slopes.setText(_translate("MicroTomographyAnalyzer", "Save"))
        self.groupBox_5.setTitle(_translate("MicroTomographyAnalyzer", "Measure polymer level:"))
        self.sampling_rule.setItemText(0, _translate("MicroTomographyAnalyzer", "Minimum within region of interest"))
        self.sampling_rule.setItemText(1, _translate("MicroTomographyAnalyzer", "Closest substantial minimum to expected value"))
        self.start_sampling.setText(_translate("MicroTomographyAnalyzer", "start"))
        self.label_8.setText(_translate("MicroTomographyAnalyzer", "Extrema max dist"))
        self.save_polymer_level.setText(_translate("MicroTomographyAnalyzer", "Save"))
        self.pushButton.setText(_translate("MicroTomographyAnalyzer", "<<"))
        self.pushButton_2.setText(_translate("MicroTomographyAnalyzer", ">>"))
        self.groupBox_3.setTitle(_translate("MicroTomographyAnalyzer", "Select axis:"))
        self.label.setText(_translate("MicroTomographyAnalyzer", "Slice dimensions"))
        self.axis.setItemText(0, _translate("MicroTomographyAnalyzer", "yx"))
        self.axis.setItemText(1, _translate("MicroTomographyAnalyzer", "xz"))
        self.axis.setItemText(2, _translate("MicroTomographyAnalyzer", "yz"))
        self.file_info.setText(_translate("MicroTomographyAnalyzer", "No file loaded ..."))
        self.previous.setText(_translate("MicroTomographyAnalyzer", "<<"))
        self.next.setText(_translate("MicroTomographyAnalyzer", ">>"))
        self.menuOpen.setTitle(_translate("MicroTomographyAnalyzer", "Start"))
        self.menuView.setTitle(_translate("MicroTomographyAnalyzer", "View"))
        self.toolBar.setWindowTitle(_translate("MicroTomographyAnalyzer", "toolBar"))
        self.toolBar_2.setWindowTitle(_translate("MicroTomographyAnalyzer", "toolBar_2"))
        self.actionOpen.setText(_translate("MicroTomographyAnalyzer", "Open source files"))
        self.actionRotate.setText(_translate("MicroTomographyAnalyzer", "Rotate tensor"))
        self.actionDetect.setText(_translate("MicroTomographyAnalyzer", "Detect columns"))
        self.actionImbibition.setText(_translate("MicroTomographyAnalyzer", "Find imbibition front"))
        self.actionSave.setText(_translate("MicroTomographyAnalyzer", "Save current tensor"))
        self.actionDisplay_xy_slices.setText(_translate("MicroTomographyAnalyzer", "Display xy slices"))
        self.actionDisplay_xz_slices.setText(_translate("MicroTomographyAnalyzer", "Display xz slices"))
        self.actionDisplay_yz_slices.setText(_translate("MicroTomographyAnalyzer", "Display yz slices"))
        self.actionShow_slices.setText(_translate("MicroTomographyAnalyzer", "Show slices"))
        self.actionShow_Detected_colum_view.setText(_translate("MicroTomographyAnalyzer", "Show detected colum view"))
        self.actionShow_columnwise_imbibition_front.setText(_translate("MicroTomographyAnalyzer", "Show columnwise imbibition front"))
        self.actionSlice_tensor.setText(_translate("MicroTomographyAnalyzer", "Slice tensor"))
        self.actionOpen_Tensor.setText(_translate("MicroTomographyAnalyzer", "Open Tensor"))

from imagedisplay import ImageDisplay
