# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'capillary_interactive.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_kapilar(object):
    def setupUi(self, kapilar):
        kapilar.setObjectName("kapilar")
        kapilar.resize(854, 525)
        self.centralwidget = QtWidgets.QWidget(kapilar)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.frame = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_plot = ImageDisplay(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_plot.sizePolicy().hasHeightForWidth())
        self.main_plot.setSizePolicy(sizePolicy)
        self.main_plot.setText("")
        self.main_plot.setObjectName("main_plot")
        self.verticalLayout.addWidget(self.main_plot)
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.widget = QtWidgets.QWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.filenames = QtWidgets.QLineEdit(self.widget_2)
        self.filenames.setMinimumSize(QtCore.QSize(150, 0))
        self.filenames.setMaximumSize(QtCore.QSize(150, 16777215))
        self.filenames.setObjectName("filenames")
        self.horizontalLayout.addWidget(self.filenames)
        self.apply_cascades = QtWidgets.QCheckBox(self.widget_2)
        self.apply_cascades.setObjectName("apply_cascades")
        self.horizontalLayout.addWidget(self.apply_cascades)
        self.file_number = QtWidgets.QSpinBox(self.widget_2)
        self.file_number.setMinimumSize(QtCore.QSize(80, 0))
        self.file_number.setMaximumSize(QtCore.QSize(100, 16777215))
        self.file_number.setMaximum(999999999)
        self.file_number.setObjectName("file_number")
        self.horizontalLayout.addWidget(self.file_number)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.previous_image = QtWidgets.QPushButton(self.widget_2)
        self.previous_image.setMaximumSize(QtCore.QSize(35, 16777215))
        self.previous_image.setObjectName("previous_image")
        self.horizontalLayout.addWidget(self.previous_image)
        self.next_image = QtWidgets.QPushButton(self.widget_2)
        self.next_image.setMaximumSize(QtCore.QSize(35, 16777215))
        self.next_image.setObjectName("next_image")
        self.horizontalLayout.addWidget(self.next_image)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.verticalLayout.addWidget(self.widget)
        self.scrollArea = QtWidgets.QScrollArea(self.splitter)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 379, 1059))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.view_2d_cascade = LimitedDropTree(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view_2d_cascade.sizePolicy().hasHeightForWidth())
        self.view_2d_cascade.setSizePolicy(sizePolicy)
        self.view_2d_cascade.setObjectName("view_2d_cascade")
        self.verticalLayout_5.addWidget(self.view_2d_cascade)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.combo_box_2d_cascade = QtWidgets.QComboBox(self.groupBox)
        self.combo_box_2d_cascade.setObjectName("combo_box_2d_cascade")
        self.horizontalLayout_2.addWidget(self.combo_box_2d_cascade)
        self.add_to_2d_cascade = QtWidgets.QPushButton(self.groupBox)
        self.add_to_2d_cascade.setMaximumSize(QtCore.QSize(20, 16777215))
        self.add_to_2d_cascade.setObjectName("add_to_2d_cascade")
        self.horizontalLayout_2.addWidget(self.add_to_2d_cascade)
        self.remove_from_2d_cascade = QtWidgets.QPushButton(self.groupBox)
        self.remove_from_2d_cascade.setMaximumSize(QtCore.QSize(20, 16777215))
        self.remove_from_2d_cascade.setObjectName("remove_from_2d_cascade")
        self.horizontalLayout_2.addWidget(self.remove_from_2d_cascade)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.load_2d_cascade = QtWidgets.QPushButton(self.groupBox)
        self.load_2d_cascade.setMaximumSize(QtCore.QSize(50, 16777215))
        self.load_2d_cascade.setObjectName("load_2d_cascade")
        self.horizontalLayout_2.addWidget(self.load_2d_cascade)
        self.save_2d_cascade = QtWidgets.QPushButton(self.groupBox)
        self.save_2d_cascade.setMaximumSize(QtCore.QSize(50, 16777215))
        self.save_2d_cascade.setObjectName("save_2d_cascade")
        self.horizontalLayout_2.addWidget(self.save_2d_cascade)
        self.apply_cascade_2d = QtWidgets.QPushButton(self.groupBox)
        self.apply_cascade_2d.setMaximumSize(QtCore.QSize(40, 16777215))
        self.apply_cascade_2d.setObjectName("apply_cascade_2d")
        self.horizontalLayout_2.addWidget(self.apply_cascade_2d)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.error_2d_cascade = QtWidgets.QTextEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.error_2d_cascade.sizePolicy().hasHeightForWidth())
        self.error_2d_cascade.setSizePolicy(sizePolicy)
        self.error_2d_cascade.setObjectName("error_2d_cascade")
        self.verticalLayout_5.addWidget(self.error_2d_cascade)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.view_1d_cascade_0 = QtWidgets.QTreeView(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view_1d_cascade_0.sizePolicy().hasHeightForWidth())
        self.view_1d_cascade_0.setSizePolicy(sizePolicy)
        self.view_1d_cascade_0.setObjectName("view_1d_cascade_0")
        self.verticalLayout_4.addWidget(self.view_1d_cascade_0)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.combo_box_1d_cascade_0 = QtWidgets.QComboBox(self.groupBox_2)
        self.combo_box_1d_cascade_0.setObjectName("combo_box_1d_cascade_0")
        self.horizontalLayout_4.addWidget(self.combo_box_1d_cascade_0)
        self.add_to_1d_cascade_0 = QtWidgets.QPushButton(self.groupBox_2)
        self.add_to_1d_cascade_0.setObjectName("add_to_1d_cascade_0")
        self.horizontalLayout_4.addWidget(self.add_to_1d_cascade_0)
        self.load_1d_cascade_0 = QtWidgets.QPushButton(self.groupBox_2)
        self.load_1d_cascade_0.setObjectName("load_1d_cascade_0")
        self.horizontalLayout_4.addWidget(self.load_1d_cascade_0)
        self.safe_1d_cascade_0 = QtWidgets.QPushButton(self.groupBox_2)
        self.safe_1d_cascade_0.setObjectName("safe_1d_cascade_0")
        self.horizontalLayout_4.addWidget(self.safe_1d_cascade_0)
        self.apply_cascade_1d_0 = QtWidgets.QPushButton(self.groupBox_2)
        self.apply_cascade_1d_0.setMaximumSize(QtCore.QSize(25, 16777215))
        self.apply_cascade_1d_0.setObjectName("apply_cascade_1d_0")
        self.horizontalLayout_4.addWidget(self.apply_cascade_1d_0)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.error_2d_cascade_2 = QtWidgets.QTextEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.error_2d_cascade_2.sizePolicy().hasHeightForWidth())
        self.error_2d_cascade_2.setSizePolicy(sizePolicy)
        self.error_2d_cascade_2.setObjectName("error_2d_cascade_2")
        self.verticalLayout_4.addWidget(self.error_2d_cascade_2)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.view_1d_cascade_1 = QtWidgets.QTreeView(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view_1d_cascade_1.sizePolicy().hasHeightForWidth())
        self.view_1d_cascade_1.setSizePolicy(sizePolicy)
        self.view_1d_cascade_1.setObjectName("view_1d_cascade_1")
        self.verticalLayout_3.addWidget(self.view_1d_cascade_1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.combo_box_1d_cascade_1 = QtWidgets.QComboBox(self.groupBox_4)
        self.combo_box_1d_cascade_1.setObjectName("combo_box_1d_cascade_1")
        self.horizontalLayout_5.addWidget(self.combo_box_1d_cascade_1)
        self.add_to_1d_cascade_1 = QtWidgets.QPushButton(self.groupBox_4)
        self.add_to_1d_cascade_1.setObjectName("add_to_1d_cascade_1")
        self.horizontalLayout_5.addWidget(self.add_to_1d_cascade_1)
        self.load_1d_cascade_1 = QtWidgets.QPushButton(self.groupBox_4)
        self.load_1d_cascade_1.setObjectName("load_1d_cascade_1")
        self.horizontalLayout_5.addWidget(self.load_1d_cascade_1)
        self.save_1d_cascade_1 = QtWidgets.QPushButton(self.groupBox_4)
        self.save_1d_cascade_1.setObjectName("save_1d_cascade_1")
        self.horizontalLayout_5.addWidget(self.save_1d_cascade_1)
        self.apply_cascade_1d_1 = QtWidgets.QPushButton(self.groupBox_4)
        self.apply_cascade_1d_1.setMaximumSize(QtCore.QSize(25, 16777215))
        self.apply_cascade_1d_1.setObjectName("apply_cascade_1d_1")
        self.horizontalLayout_5.addWidget(self.apply_cascade_1d_1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.error_2d_cascade_3 = QtWidgets.QTextEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.error_2d_cascade_3.sizePolicy().hasHeightForWidth())
        self.error_2d_cascade_3.setSizePolicy(sizePolicy)
        self.error_2d_cascade_3.setObjectName("error_2d_cascade_3")
        self.verticalLayout_3.addWidget(self.error_2d_cascade_3)
        self.verticalLayout_6.addWidget(self.groupBox_4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.addWidget(self.splitter)
        kapilar.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(kapilar)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 854, 17))
        self.menuBar.setObjectName("menuBar")
        self.menuOpen_files = QtWidgets.QMenu(self.menuBar)
        self.menuOpen_files.setObjectName("menuOpen_files")
        kapilar.setMenuBar(self.menuBar)
        self.open_file = QtWidgets.QAction(kapilar)
        self.open_file.setObjectName("open_file")
        self.exit = QtWidgets.QAction(kapilar)
        self.exit.setObjectName("exit")
        self.actionConfigure_output = QtWidgets.QAction(kapilar)
        self.actionConfigure_output.setObjectName("actionConfigure_output")
        self.menuOpen_files.addAction(self.open_file)
        self.menuOpen_files.addAction(self.actionConfigure_output)
        self.menuOpen_files.addAction(self.exit)
        self.menuBar.addAction(self.menuOpen_files.menuAction())

        self.retranslateUi(kapilar)
        QtCore.QMetaObject.connectSlotsByName(kapilar)

    def retranslateUi(self, kapilar):
        _translate = QtCore.QCoreApplication.translate
        kapilar.setWindowTitle(_translate("kapilar", "KAPILAR"))
        self.apply_cascades.setText(_translate("kapilar", "Apply cascades"))
        self.previous_image.setText(_translate("kapilar", "<<"))
        self.next_image.setText(_translate("kapilar", ">>"))
        self.groupBox.setTitle(_translate("kapilar", "Filter cascade: 2D-Plot"))
        self.add_to_2d_cascade.setText(_translate("kapilar", "+"))
        self.remove_from_2d_cascade.setText(_translate("kapilar", "-"))
        self.load_2d_cascade.setText(_translate("kapilar", "Load ..."))
        self.save_2d_cascade.setText(_translate("kapilar", "Save ..."))
        self.apply_cascade_2d.setText(_translate("kapilar", "Apply"))
        self.groupBox_2.setTitle(_translate("kapilar", "Filter cascade: 1D-Plot"))
        self.add_to_1d_cascade_0.setText(_translate("kapilar", "Add"))
        self.load_1d_cascade_0.setText(_translate("kapilar", "Load ..."))
        self.safe_1d_cascade_0.setText(_translate("kapilar", "Save ..."))
        self.apply_cascade_1d_0.setText(_translate("kapilar", "✓"))
        self.groupBox_3.setTitle(_translate("kapilar", "Custom classifier"))
        self.groupBox_4.setTitle(_translate("kapilar", "Filter cascade: 1D-Plot"))
        self.add_to_1d_cascade_1.setText(_translate("kapilar", "Add ..."))
        self.load_1d_cascade_1.setText(_translate("kapilar", "Load ..."))
        self.save_1d_cascade_1.setText(_translate("kapilar", "Save ..."))
        self.apply_cascade_1d_1.setText(_translate("kapilar", "✓"))
        self.menuOpen_files.setTitle(_translate("kapilar", "File"))
        self.open_file.setText(_translate("kapilar", "Open .."))
        self.exit.setText(_translate("kapilar", "Exit"))
        self.actionConfigure_output.setText(_translate("kapilar", "Configure output ..."))

from imagedisplay import ImageDisplay
from limiteddroptree import LimitedDropTree
