# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'capillary_interactive.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_kapilar(object):
    def setupUi(self, kapilar):
        kapilar.setObjectName("kapilar")
        kapilar.resize(934, 810)
        self.centralwidget = QtWidgets.QWidget(kapilar)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.frame = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.main_plot = ImageDisplay(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_plot.sizePolicy().hasHeightForWidth())
        self.main_plot.setSizePolicy(sizePolicy)
        self.main_plot.setText("")
        self.main_plot.setObjectName("main_plot")
        self.verticalLayout_3.addWidget(self.main_plot)
        self.verticalLayout.addWidget(self.frame_2)
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.widget = QtWidgets.QWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.filenames = QtWidgets.QLineEdit(self.widget_2)
        self.filenames.setMinimumSize(QtCore.QSize(150, 0))
        self.filenames.setMaximumSize(QtCore.QSize(150, 16777215))
        self.filenames.setObjectName("filenames")
        self.horizontalLayout.addWidget(self.filenames)
        self.show_image = QtWidgets.QPushButton(self.widget_2)
        self.show_image.setObjectName("show_image")
        self.horizontalLayout.addWidget(self.show_image)
        self.file_number = QtWidgets.QSpinBox(self.widget_2)
        self.file_number.setMinimumSize(QtCore.QSize(80, 0))
        self.file_number.setMaximumSize(QtCore.QSize(100, 16777215))
        self.file_number.setMaximum(999999999)
        self.file_number.setObjectName("file_number")
        self.horizontalLayout.addWidget(self.file_number)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.previous_image = QtWidgets.QPushButton(self.widget_2)
        self.previous_image.setMaximumSize(QtCore.QSize(35, 16777215))
        self.previous_image.setObjectName("previous_image")
        self.horizontalLayout.addWidget(self.previous_image)
        self.next_image = QtWidgets.QPushButton(self.widget_2)
        self.next_image.setMaximumSize(QtCore.QSize(35, 16777215))
        self.next_image.setObjectName("next_image")
        self.horizontalLayout.addWidget(self.next_image)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.verticalLayout.addWidget(self.widget)
        self.scrollArea = QtWidgets.QScrollArea(self.splitter)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 420, 860))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.message_cascade_1 = QtWidgets.QLineEdit(self.groupBox)
        self.message_cascade_1.setObjectName("message_cascade_1")
        self.horizontalLayout_6.addWidget(self.message_cascade_1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.load_assign_cascade_1 = QtWidgets.QCheckBox(self.groupBox)
        self.load_assign_cascade_1.setObjectName("load_assign_cascade_1")
        self.horizontalLayout_6.addWidget(self.load_assign_cascade_1)
        self.load_attributions_cascade_1 = QtWidgets.QPushButton(self.groupBox)
        self.load_attributions_cascade_1.setObjectName("load_attributions_cascade_1")
        self.horizontalLayout_6.addWidget(self.load_attributions_cascade_1)
        self.specify_output_cascade_1 = QtWidgets.QPushButton(self.groupBox)
        self.specify_output_cascade_1.setObjectName("specify_output_cascade_1")
        self.horizontalLayout_6.addWidget(self.specify_output_cascade_1)
        self.gridLayout.addLayout(self.horizontalLayout_6, 3, 0, 1, 1)
        self.error_cascade_1 = QtWidgets.QTextEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.error_cascade_1.sizePolicy().hasHeightForWidth())
        self.error_cascade_1.setSizePolicy(sizePolicy)
        self.error_cascade_1.setMinimumSize(QtCore.QSize(0, 50))
        self.error_cascade_1.setObjectName("error_cascade_1")
        self.gridLayout.addWidget(self.error_cascade_1, 4, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.combo_box_cascade_1 = QtWidgets.QComboBox(self.groupBox)
        self.combo_box_cascade_1.setObjectName("combo_box_cascade_1")
        self.horizontalLayout_2.addWidget(self.combo_box_cascade_1)
        self.add_to_cascade_1 = QtWidgets.QPushButton(self.groupBox)
        self.add_to_cascade_1.setMaximumSize(QtCore.QSize(20, 16777215))
        self.add_to_cascade_1.setObjectName("add_to_cascade_1")
        self.horizontalLayout_2.addWidget(self.add_to_cascade_1)
        self.remove_from_cascade_1 = QtWidgets.QPushButton(self.groupBox)
        self.remove_from_cascade_1.setMaximumSize(QtCore.QSize(20, 16777215))
        self.remove_from_cascade_1.setObjectName("remove_from_cascade_1")
        self.horizontalLayout_2.addWidget(self.remove_from_cascade_1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.load_cascade_1 = QtWidgets.QPushButton(self.groupBox)
        self.load_cascade_1.setMaximumSize(QtCore.QSize(50, 16777215))
        self.load_cascade_1.setObjectName("load_cascade_1")
        self.horizontalLayout_2.addWidget(self.load_cascade_1)
        self.save_cascade_1 = QtWidgets.QPushButton(self.groupBox)
        self.save_cascade_1.setMaximumSize(QtCore.QSize(50, 16777215))
        self.save_cascade_1.setObjectName("save_cascade_1")
        self.horizontalLayout_2.addWidget(self.save_cascade_1)
        self.apply_cascade_1 = QtWidgets.QPushButton(self.groupBox)
        self.apply_cascade_1.setMaximumSize(QtCore.QSize(40, 16777215))
        self.apply_cascade_1.setObjectName("apply_cascade_1")
        self.horizontalLayout_2.addWidget(self.apply_cascade_1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.view_cascade_1 = LimitedDropTree(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view_cascade_1.sizePolicy().hasHeightForWidth())
        self.view_cascade_1.setSizePolicy(sizePolicy)
        self.view_cascade_1.setObjectName("view_cascade_1")
        self.gridLayout.addWidget(self.view_cascade_1, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 3)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.view_cascade_2 = LimitedDropTree(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view_cascade_2.sizePolicy().hasHeightForWidth())
        self.view_cascade_2.setSizePolicy(sizePolicy)
        self.view_cascade_2.setObjectName("view_cascade_2")
        self.gridLayout_2.addWidget(self.view_cascade_2, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.combo_box_cascade_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.combo_box_cascade_2.setObjectName("combo_box_cascade_2")
        self.horizontalLayout_4.addWidget(self.combo_box_cascade_2)
        self.add_to_cascade_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.add_to_cascade_2.setMaximumSize(QtCore.QSize(20, 16777215))
        self.add_to_cascade_2.setObjectName("add_to_cascade_2")
        self.horizontalLayout_4.addWidget(self.add_to_cascade_2)
        self.remove_from_cascade_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.remove_from_cascade_2.setMaximumSize(QtCore.QSize(20, 16777215))
        self.remove_from_cascade_2.setObjectName("remove_from_cascade_2")
        self.horizontalLayout_4.addWidget(self.remove_from_cascade_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.load_cascade_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.load_cascade_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.load_cascade_2.setObjectName("load_cascade_2")
        self.horizontalLayout_4.addWidget(self.load_cascade_2)
        self.save_cascade_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.save_cascade_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.save_cascade_2.setObjectName("save_cascade_2")
        self.horizontalLayout_4.addWidget(self.save_cascade_2)
        self.apply_cascade_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.apply_cascade_2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.apply_cascade_2.setObjectName("apply_cascade_2")
        self.horizontalLayout_4.addWidget(self.apply_cascade_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.error_cascade_2 = QtWidgets.QTextEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.error_cascade_2.sizePolicy().hasHeightForWidth())
        self.error_cascade_2.setSizePolicy(sizePolicy)
        self.error_cascade_2.setMinimumSize(QtCore.QSize(0, 50))
        self.error_cascade_2.setObjectName("error_cascade_2")
        self.gridLayout_2.addWidget(self.error_cascade_2, 3, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.message_cascade_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.message_cascade_2.setObjectName("message_cascade_2")
        self.horizontalLayout_7.addWidget(self.message_cascade_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.load_assign_cascade_2 = QtWidgets.QCheckBox(self.groupBox_2)
        self.load_assign_cascade_2.setObjectName("load_assign_cascade_2")
        self.horizontalLayout_7.addWidget(self.load_assign_cascade_2)
        self.load_attributions_cascade_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.load_attributions_cascade_2.setObjectName("load_attributions_cascade_2")
        self.horizontalLayout_7.addWidget(self.load_attributions_cascade_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 2, 0, 1, 1)
        self.gridLayout_2.setRowStretch(0, 3)
        self.gridLayout_2.setRowStretch(2, 1)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.draw_vertica_lines = QtWidgets.QCheckBox(self.groupBox_4)
        self.draw_vertica_lines.setObjectName("draw_vertica_lines")
        self.horizontalLayout_5.addWidget(self.draw_vertica_lines)
        self.use_cropped = QtWidgets.QCheckBox(self.groupBox_4)
        self.use_cropped.setObjectName("use_cropped")
        self.horizontalLayout_5.addWidget(self.use_cropped)
        self.verticalLayout_6.addWidget(self.groupBox_4)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6.addWidget(self.groupBox_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.addWidget(self.splitter)
        kapilar.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(kapilar)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 934, 17))
        self.menuBar.setObjectName("menuBar")
        self.menuOpen_files = QtWidgets.QMenu(self.menuBar)
        self.menuOpen_files.setObjectName("menuOpen_files")
        kapilar.setMenuBar(self.menuBar)
        self.open_file = QtWidgets.QAction(kapilar)
        self.open_file.setObjectName("open_file")
        self.exit = QtWidgets.QAction(kapilar)
        self.exit.setObjectName("exit")
        self.toggle_colors = QtWidgets.QAction(kapilar)
        self.toggle_colors.setObjectName("toggle_colors")
        self.menuOpen_files.addAction(self.open_file)
        self.menuOpen_files.addAction(self.toggle_colors)
        self.menuOpen_files.addAction(self.exit)
        self.menuBar.addAction(self.menuOpen_files.menuAction())

        self.retranslateUi(kapilar)
        QtCore.QMetaObject.connectSlotsByName(kapilar)

    def retranslateUi(self, kapilar):
        _translate = QtCore.QCoreApplication.translate
        kapilar.setWindowTitle(_translate("kapilar", "KAPILAR"))
        self.show_image.setText(_translate("kapilar", "Show image"))
        self.previous_image.setText(_translate("kapilar", "<<"))
        self.next_image.setText(_translate("kapilar", ">>"))
        self.groupBox.setTitle(_translate("kapilar", "Filter cascade (1)"))
        self.load_assign_cascade_1.setText(_translate("kapilar", "Load and assign"))
        self.load_attributions_cascade_1.setText(_translate("kapilar", "Set attributions ..."))
        self.specify_output_cascade_1.setText(_translate("kapilar", "Specify output ..."))
        self.add_to_cascade_1.setText(_translate("kapilar", "+"))
        self.remove_from_cascade_1.setText(_translate("kapilar", "-"))
        self.load_cascade_1.setText(_translate("kapilar", "Load ..."))
        self.save_cascade_1.setText(_translate("kapilar", "Save ..."))
        self.apply_cascade_1.setText(_translate("kapilar", "Apply"))
        self.groupBox_2.setTitle(_translate("kapilar", "Filter cascade (2)"))
        self.add_to_cascade_2.setText(_translate("kapilar", "+"))
        self.remove_from_cascade_2.setText(_translate("kapilar", "-"))
        self.load_cascade_2.setText(_translate("kapilar", "Load ..."))
        self.save_cascade_2.setText(_translate("kapilar", "Save ..."))
        self.apply_cascade_2.setText(_translate("kapilar", "Apply"))
        self.load_assign_cascade_2.setText(_translate("kapilar", "Load and assign"))
        self.load_attributions_cascade_2.setText(_translate("kapilar", "Set attributions file ..."))
        self.groupBox_4.setTitle(_translate("kapilar", "Display options"))
        self.draw_vertica_lines.setText(_translate("kapilar", "Draw vertical lines"))
        self.use_cropped.setText(_translate("kapilar", "Original in background"))
        self.groupBox_3.setTitle(_translate("kapilar", "Custom classifier"))
        self.menuOpen_files.setTitle(_translate("kapilar", "File"))
        self.open_file.setText(_translate("kapilar", "Open .."))
        self.exit.setText(_translate("kapilar", "Exit"))
        self.toggle_colors.setText(_translate("kapilar", "Toggle colors"))

from imagedisplay import ImageDisplay
from limiteddroptree import LimitedDropTree
